# Generated by Django 3.2.6 on 2021-08-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contrib',
            new_name='content',
        ),
    ]
